version: '3'
services:
  alpine:
    build:
      context: ./alpine
    command: 'ps aux'
    container_name: 'run-non-root-alpine'
    image: 'creemama/run-non-root:1.4.0-alpine-3.9-1'
  centos:
    build:
      context: ./centos
    command: 'ps aux'
    container_name: 'run-non-root-centos'
    image: 'creemama/run-non-root:1.4.0-centos-7'
  certbot:
    build:
      context: ./certbot
    command: '-- certbot --help'
    container_name: 'run-non-root-certbot'
    environment:
      - RUN_NON_ROOT_GID=${RUN_NON_ROOT_GID-}
      - RUN_NON_ROOT_UID=${RUN_NON_ROOT_UID-}
    image: 'creemama/run-non-root:1.4.0-certbot-0.31.0'
    volumes:
      - "${LETS_ENCRYPT_PATH-}:/etc/letsencrypt"
  certbot-renew-cron:
    build:
      context: ./certbot-renew-cron
    container_name: 'run-non-root-certbot-renew-cron'
    image: 'creemama/run-non-root:1.4.0-certbot-0.31.0-renew-cron'
    environment:
      - RUN_NON_ROOT_GID=${RUN_NON_ROOT_GID-}
      - RUN_NON_ROOT_UID=${RUN_NON_ROOT_UID-}
    volumes:
      - "${LETS_ENCRYPT_PATH-}:/etc/letsencrypt"
  fedora:
    build:
      context: ./fedora
    command: 'ps aux'
    container_name: 'run-non-root-fedora'
    image: 'creemama/run-non-root:1.4.0-fedora-29-1'
  debian:
    build:
      context: ./debian
    command: 'ps aux'
    container_name: 'run-non-root-debian'
    image: 'creemama/run-non-root:1.4.0-debian-9.7-1'
  node:
    build:
      context: ./node
    container_name: 'run-non-root-node'
    environment:
      - RUN_NON_ROOT_GID=${RUN_NON_ROOT_GID-}
      - RUN_NON_ROOT_UID=${RUN_NON_ROOT_UID-}
    image: 'creemama/run-non-root:1.4.0-node-10.15.1-1'
  ubuntu:
    build:
      context: ./ubuntu
    command: 'ps aux'
    container_name: 'run-non-root-ubuntu'
    image: 'creemama/run-non-root:1.4.0-ubuntu-18.04'
