version: '3'
services:
  alpine:
    build:
      context: ./alpine
    # command: 'ps aux'
    command: -- /bin/sh -c "while :; do echo 'Hit CTRL+C'; sleep 1d; done"
    container_name: 'run-non-root-alpine'
    image: 'creemama/run-non-root:1.5.1-alpine'
    read_only: true
    security_opt:
      - no-new-privileges
    tmpfs:
      - /home/nonroot
    volumes:
      - /etc
      - /var/mail/nonroot
  centos:
    build:
      context: ./centos
    # command: 'ps aux'
    command: -- /bin/sh -c "while :; do echo 'Hit CTRL+C'; sleep 1d; done"
    container_name: 'run-non-root-centos'
    image: 'creemama/run-non-root:1.5.1-centos'
    read_only: true
    security_opt:
      - no-new-privileges
    tmpfs:
      - /home/nonroot
    volumes:
      - /etc
  certbot:
    build:
      context: ./certbot
    command: '-- certbot --help'
    container_name: 'run-non-root-certbot'
    environment:
      - RUN_NON_ROOT_GID=${RUN_NON_ROOT_GID-}
      - RUN_NON_ROOT_UID=${RUN_NON_ROOT_UID-}
    image: 'creemama/run-non-root:1.5.1-certbot'
    read_only: true
    security_opt:
      - no-new-privileges
    tmpfs:
      - /home/certbot
      - /tmp
      - /var/log
      - /var/mail/certbot
    volumes:
      - /etc
      - "${LETS_ENCRYPT_PATH-}:/etc/letsencrypt"
  certbot-renew-cron:
    build:
      context: ./certbot-renew-cron
    container_name: 'run-non-root-certbot-renew-cron'
    image: 'creemama/run-non-root:1.5.1-certbot-renew-cron'
    environment:
      - RUN_NON_ROOT_GID=${RUN_NON_ROOT_GID-}
      - RUN_NON_ROOT_UID=${RUN_NON_ROOT_UID-}
    read_only: true
    security_opt:
      - no-new-privileges
    tmpfs:
      - /home/certbot
      - /tmp
      - /var/log
      - /var/mail/certbot
    volumes:
      - /etc
      - "${LETS_ENCRYPT_PATH-}:/etc/letsencrypt"
  debian:
    build:
      context: ./debian
    # command: 'ps aux'
    command: -- /bin/sh -c "while :; do echo 'Hit CTRL+C'; sleep 1d; done"
    container_name: 'run-non-root-debian'
    image: 'creemama/run-non-root:1.5.1-debian'
    read_only: true
    security_opt:
      - no-new-privileges
    tmpfs:
      - /home/nonroot
    volumes:
      - /etc
  fedora:
    build:
      context: ./fedora
    # command: 'ps aux'
    command: -- /bin/sh -c "while :; do echo 'Hit CTRL+C'; sleep 1d; done"
    container_name: 'run-non-root-fedora'
    image: 'creemama/run-non-root:1.5.1-fedora'
    read_only: true
    security_opt:
      - no-new-privileges
    tmpfs:
      - /home/nonroot
    volumes:
      - /etc
  node:
    build:
      context: ./node
    container_name: 'run-non-root-node'
    environment:
      # - RUN_NON_ROOT_COMMAND=node --version
      - RUN_NON_ROOT_COMMAND=/bin/sh -c "node --version && while :; do echo 'Hit CTRL+C'; sleep 1d; done"
      - RUN_NON_ROOT_GID=${RUN_NON_ROOT_GID-}
      - RUN_NON_ROOT_UID=${RUN_NON_ROOT_UID-}
    image: 'creemama/run-non-root:1.5.1-node'
    read_only: true
    security_opt:
      - no-new-privileges
    tmpfs:
      - /home/node
      - /var/log
      - /var/mail/node
    volumes:
      - /etc
  ubuntu:
    build:
      context: ./ubuntu
    # command: 'ps aux'
    command: -- /bin/sh -c "while :; do echo 'Hit CTRL+C'; sleep 1d; done"
    container_name: 'run-non-root-ubuntu'
    image: 'creemama/run-non-root:1.5.1-ubuntu'
    read_only: true
    security_opt:
      - no-new-privileges
    tmpfs:
      - /home/nonroot
    volumes:
      - /etc
